### ISSUE TITLE
GitHub policy violation

### ISSUE THREAD

**Issue by dragonDScript** [conwnet/github1s#51] opened 2021-02-10 17:58 UTC
https://docs.github.com/en/github/site-policy/github-trademark-policy#what-is-a-github-trademark-policy-violation
Github1s may be violating github's policies.

**Comment by simonsan** [comment] 2021-02-10 22:57
Can you elaborate why and how you think it may violate it? At first glance I don't see anything special regarding this topic in that link, only some stuff about some logos and irritation. Personally `github1s` is not irritating me, it's clear it's github with a visual code theme. Both Microsoft products. I could even guess they could be happy someone did this. :)

**Comment by dragonDScript** [comment] 2021-02-11 15:33
> Can you elaborate why and how you think it may violate it? At first glance I don't see anything special regarding this topic in that link, only some stuff about some logos and irritation. Personally `github1s` is not irritating me, it's clear it's github with a visual code theme. Both Microsoft products. I could even guess they could be happy someone did this. :)

GitHub1s can be confused with GitHub. GitHub1s uses the GitHub logo and its name in its domain and website. As an anecdotal case, my friend and another person thought that github1s was somehow related with github, which it's not.

**Comment by conwnet** [comment] 2021-02-12 05:51
Sorry about that, In my original intention, this GitHub logo in the activity bar just want to provide an quick way to jump back GitHub, we will give significant hints to tell users that **GitHub1s is NOT official website** next

**Comment by JammSpread** [comment] 2021-02-12 18:21
I think much of the issue is that the GitHub icon's use (in `github1s`) is pretty similar to the UI of GitHub Codespaces. Which may be misleading in nature.
> ![githubcodespaces](https://user-images.githubusercontent.com/61063879/107806698-29fbe380-6d35-11eb-87c1-6c2ea8dfb9af.png)

**Comment by dragonDScript** [comment] 2021-02-12 18:59
Great, thanks for making this change. I really love this project!

**Comment by dragonDScript** [comment] 2021-02-19 15:23
> I think much of the issue is that the GitHub icon's use (in `github1s`) is pretty similar to the UI of GitHub Codespaces. Which may be misleading in nature.
> 
> > _**GitHub Codespaces**_
> > ![githubcodespaces](https://user-images.githubusercontent.com/61063879/107806698-29fbe380-6d35-11eb-87c1-6c2ea8dfb9af.png)

Yep.

**Comment by Siddhant-K-code** [comment] 2021-02-21 01:42
Since This thing is fixed and now release has to make aware that this not official: 
![image](https://user-images.githubusercontent.com/55068936/108613041-fa736800-7413-11eb-9651-fbdc86e7cb10.png)

So, I am Closing this issue.

**Closed by Siddhant-K-code** 2021-02-21 01:42 UTC
Labels: help wanted
