### ISSUE TITLE
Please add ipynb files readable too (in the form of .py files) [Feature Request]

### ISSUE THREAD

**Issue by elvinaqa** [conwnet/github1s#108] opened 2021-02-13 14:31 UTC
There are tons of pushed code in the ipynb files from either Jupyter Notebook or Google colab, which is not currently supported by github1s. I would highly recommend adding that feature to convert ipynb files to .py files and make it readable in the browser as well. 

Thanks. 
Great project!

**Comment by Siddhant-K-code** [comment] 2021-02-13 17:04
we are currently trying to implement Jupyter Notebook viewer, and this issue is a duplicate of #77

**Closed by Siddhant-K-code** 2021-02-13 17:04 UTC

**Comment by elvinaqa** [comment] 2021-02-13 18:28
Sorry didnt see that. Cool!
